[colors.primary]
background = "#282828"
foreground = "#eeeeee"

[colors.normal]
black = "#1f2229"
red = "#d41919"
green = "#5ebdab"
yellow = "#fea44c"
blue = "#367bf0"
magenta = "#bf25ed"
cyan = "#49aee6"
white = "#e6e6e6"

[colors.bright]
black = "#8c42ab"
red = "#ec0101"
green = "#47d489"
yellow = "#ff8a18"
blue = "#277fff"
magenta = "#d71655"
cyan = "#05a1f7"
white = "#ffffff"
