# Colors

# Default colors
  [colors.primary]
    background = "#1F2229"
    foreground = "#E6E6E6"
  
  # Normal colors
  [colors.normal]
    black = "#1F2229"
    red = "#D41919"
    green = "#5EBDAB"
    yellow = "#FEA44C"
    blue = "#367BF0"
    magenta = "#BF25ED"
    cyan = "#49AEE6"
    white = "#E6E6E6"
  
  # Bright colors
  [colors.bright]
    black = "#8C42AB"
    red = "#EC0101"
    green = "#47D489"
    yellow = "#FF8A18"
    blue = "#277FFF"
    magenta = "#D71655"
    cyan = "#05A1F7"
    white = "#FFFFFF"

