#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a steam desktop ='^3' 

# Wallpaper
feh -z --bg-scale Pictures/wallpapers/
# Polybar
./.config/polybar/launch.sh --grayblocks

# Startup
picom &
mpd
steam
